### ISSUE TITLE
[Discussion] Request/Response messaging

### ISSUE THREAD

**Issue by sbstp** [cylonn/blueprint#4]
How should we handle replies in the system? For instance, a plugin might ask a service for some information, or a service might want to notify a plugin that it could not complete its request.

__Should we use different namespaces?__
`ns/req/info` -> `ns/res/info`

__Should the message's type be the same?__
The sender would have to match ID.
`ns/info` (id=3) -> `ns/info` (id=3)

__How can we make sure that a thirdyparty properly identifies messages' origin? (request vs response)__
We could add an `origin` field to the messages, but I don't think it's the best solution.

**Comment by alxgnon** [comment]
#### I see it like this:

- For a query/response (ask/reply) pair, message `type` is the same up to the last term.
- The last term of the `type` differs to tell between a ask and a reply.
- `id` matches, to ensure replies find their way back.

#### Ask
```json
{
    "type": "plugin/list/ask",
    "id": "plzrespond"
}
```

#### Reply
```json
{
    "type": "plugin/list/reply",
    "id": "plzrespond",
    "plugins": [ ... ]
}
```

**Comment by SBSTP** [comment]
A lot of calls (in the `irc` namespace, for instance) introduce the possibility of failure. The IRC client might not be connected, or there might be network failure. Should all of the calls have an `ask/reply` part? I don't think that would be ergonomic.

[JSON-RPC](http://json-rpc.org/wiki/specification) has created a precedent for this type of messaging, I think we should base our protocol on theirs. Here are the key points:

**Request** (method invocation)
```
{
  "id": "", // same as we currently have
  "method": "...", // this could be called path or type
  "params": {...}
}
```

**Response**
```
{
  "id": "", // matches the response
  "method": "", // we meed to provide this in the response too, since our architecture is not 1-to-1
  "result": {}, // result data, null if error
  "error": {} // error data, null if no error
}
```

**Notification**
```
{
  "id": "",
  "method": "",
  "params": ""
}
```

**Comment by alxgnon** [comment]
I like. Let's do the same, although `s/method/type/`

**Comment by SBSTP** [comment]
I don't know about `type`, I kinda of liked `path`.

**Comment by alxgnon** [comment]
But it's not a path

**Comment by alxgnon** [comment]
kind

**Comment by SBSTP** [comment]
yayaya im lorde

**Comment by alxgnon** [comment]
gonna fix some blueprints and make a PR

**Comment by SBSTP** [comment]
I think we need to add another distinction. If a client sends a malformed message (invalid json, invalid protocol) it should be notified. But that doesn't go through the broking system.
```
C = Client
B = Broker
MJ = Malformed JSON
EM = Error message

// Client sends malformed JSON to broker
C -> MJ -> B    =>    B -> EM -> C
// Broker replies directly to client without broadcasting anything
```
The error message can be a notification-type message.
```
{
    "id": null,
    "kind": "error",
    "error": {
        "code": "JsonError",
        "description": "ERR at index #..."
    }
}
```
I'm currently working on this, but the possible errors look like this at the moment. `code` would be the variant and description would be the `fmt::Debug` or `std::error::Error.description()`.
```rs
pub enum TemplateError<'a> {
    JsonError(BuilderError),
    MissingField(&'a str),
    InvalidType(&'a str),
}
```

**Comment by alxgnon** [comment]
In the case of a malformed message, I think it would be best to stick to the formula we already have and go for a "error" type message:
```json
{
    "id": "same-as-malformed-message",
    "kind": "same/as/malformed/message",
    "error": {
        "code": "JsonError",
        "desc": "You fail at JSON :^)"
    }
```

Just for the sake of consistency!

**Comment by alxgnon** [comment]
We should definetly put this all into the blueprints. Since my PR related to this issue isn't going to be as straightforward as I thought, I would suggest we split the work. You can take care of redefining the handshake API and I could work on the irc API. That way we can have a spec for it.

**Comment by SBSTP** [comment]
It's very likely that a malformed message won't have the `id` or `kind` field, whether it's bad json or missing fields. Actually that's the whole point of this. It can't be dealt with like the rest.

**Comment by alxgnon** [comment]
I see. In that case, your format is great. I still believe it should be "error" and not "params" though. This type of message is an error response, even if there might be no id to respond to.

How about something like this?
```json
{
    "id": null,
    "kind": "error/json",
    "error": {
        "code": "JsonError",
        "desc": "ERR at index #..."
    }
}
```

**Comment by SBSTP** [comment]
I used `error` at first, but I changed it back to  `params` to stick to the notification spec.

**Comment by alxgnon** [comment]
Alright, I'll trust your judgement.

What is your opinion on splitting the work of rewriting our blueprints related to this issue?

**Comment by SBSTP** [comment]
Yea no problem. I can rewrite `messages/handshake.md` and create a new document about malformed client/broker communication.

**Comment by alxgnon** [comment]
Great. I'll take care of the irc section.
